/**
 * Guards the Claude Code config this repo ships.
 *
 * Two failure modes, both of which are silent in the harness:
 *
 *  1. Malformed JSON. Claude Code drops the config it cannot parse and carries
 *     on, so a stray comma disables every hook in this repo with no error.
 *
 *  2. A hook or statusLine pointing at a script the repo does not ship. This is
 *     not hypothetical: settings.json referenced ~/.claude/handoff-statusline.mjs
 *     for weeks while the file existed only on one machine, generated by a plugin
 *     and never chezmoi-managed. `chezmoi apply` on a new Mac would have deployed
 *     a statusLine pointing at nothing.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const settingsPath = path.join(repoRoot, 'private_dot_claude/settings.json');
const mcpPath = path.join(repoRoot, 'private_dot_claude/dot_mcp.json');

/**
 * Files under ~/.claude/ that settings.json may reference without this repo
 * shipping them. Each entry needs a reason — an unexplained exemption here is
 * how the statusline orphan survived. Generated files belong to whatever
 * regenerates them; name that owner.
 */
const NOT_REPO_OWNED = new Map([
  [
    'handoff-statusline.mjs',
    'Generated by the handoff plugin\'s scripts/setup.mjs, which cannot run until ' +
    'the plugin cache exists. Regenerated on demand by the SessionStart hook ' +
    '(private_dot_claude/hooks/executable_session-start.sh).',
  ],
]);

/** chezmoi source name -> deployed name: strip the attribute prefixes we use. */
function sourceCandidates(relFromClaudeDir) {
  const parts = relFromClaudeDir.split('/');
  const file = parts.pop();
  const dirs = parts.map((d) => [d, `private_${d}`, `executable_${d}`]);

  // Build every prefix combination for the leaf; directories in this repo are
  // either bare or private_, and files are either bare or executable_.
  const leaves = [file, `executable_${file}`, `private_${file}`, `dot_${file}`];

  /** @type {string[]} */
  const out = [];
  const walk = (i, acc) => {
    if (i === dirs.length) {
      for (const leaf of leaves) out.push(path.join(repoRoot, 'private_dot_claude', ...acc, leaf));
      return;
    }
    for (const variant of dirs[i]) walk(i + 1, [...acc, variant]);
  };
  walk(0, []);
  return out;
}

/** Pull every ~/.claude/<path> referenced by a command string. */
function claudePathsIn(command) {
  const matches = command.matchAll(/~\/\.claude\/([A-Za-z0-9._\-/]+)/g);
  return [...matches].map((m) => m[1]);
}

function collectCommands(settings) {
  /** @type {string[]} */
  const commands = [];
  for (const entries of Object.values(settings.hooks ?? {})) {
    for (const entry of entries ?? []) {
      for (const hook of entry.hooks ?? []) {
        if (typeof hook.command === 'string') commands.push(hook.command);
      }
    }
  }
  if (typeof settings.statusLine?.command === 'string') {
    commands.push(settings.statusLine.command);
  }
  return commands;
}

test('settings.json is valid JSON', () => {
  const raw = readFileSync(settingsPath, 'utf8');
  assert.doesNotThrow(
    () => JSON.parse(raw),
    'Claude Code silently drops config it cannot parse — every hook in this repo would stop firing.',
  );
});

test('dot_mcp.json is valid JSON', () => {
  const raw = readFileSync(mcpPath, 'utf8');
  assert.doesNotThrow(() => JSON.parse(raw));
});

test('every ~/.claude script referenced by settings.json is shipped by this repo', () => {
  const settings = JSON.parse(readFileSync(settingsPath, 'utf8'));
  const commands = collectCommands(settings);

  assert.ok(commands.length > 0, 'expected at least one hook or statusLine command');

  /** @type {string[]} */
  const missing = [];
  for (const command of commands) {
    for (const rel of claudePathsIn(command)) {
      const leaf = path.basename(rel);
      if (NOT_REPO_OWNED.has(leaf)) continue;
      if (!sourceCandidates(rel).some(existsSync)) {
        missing.push(`${rel}  (referenced by: ${command})`);
      }
    }
  }

  assert.deepEqual(
    missing,
    [],
    `settings.json references ~/.claude files this repo does not ship:\n  ${missing.join('\n  ')}\n\n` +
    'A fresh `chezmoi apply` would deploy the reference without the file. Either add the ' +
    'file to private_dot_claude/, or add it to NOT_REPO_OWNED with the reason and its owner.',
  );
});

test('every NOT_REPO_OWNED exemption is actually still referenced', () => {
  const settings = JSON.parse(readFileSync(settingsPath, 'utf8'));
  const referenced = new Set(
    collectCommands(settings).flatMap(claudePathsIn).map((p) => path.basename(p)),
  );

  const stale = [...NOT_REPO_OWNED.keys()].filter((leaf) => !referenced.has(leaf));
  assert.deepEqual(
    stale,
    [],
    `NOT_REPO_OWNED exempts files settings.json no longer references: ${stale.join(', ')}. ` +
    'Remove the exemption — a stale allowlist entry hides the next orphan.',
  );
});
