#!/usr/bin/env node

/**
 * Tab Title Hook
 *
 * Notification + Stop hook that stamps the project (cwd basename) and an
 * attention glyph onto the terminal tab title via the terminalSequence
 * output field (Claude Code 2.1.141+; hooks have no /dev/tty since 2.1.139).
 *
 * While Claude works it writes its own task-summary title; this hook
 * guarantees the project name is on the tab at the moments that matter:
 *   ⏸  waiting on you (permission_prompt / agent_needs_input)
 *   ✅ done or idle (Stop / idle_prompt)
 *
 * Stop and permission/needs-input play a random ElevenLabs voice clip from
 * ~/.claude/sounds/fanfare/{stop,input}/ when present (generated by
 * fanfare-generate.mjs), since Ghostty's per-tab visual cues are limited
 * (ghostty-org/ghostty#10692). Fail-open: no clips → legacy behavior
 * (Glass.aiff chime for needs-input, silence for Stop). Set
 * CLAUDE_TAB_TITLE_SILENT=1 to disable all sound (tests do).
 *
 * Stdin is read async, not via readFileSync('/dev/stdin'): the sync read
 * intermittently throws EAGAIN when stdin is a non-blocking pipe, and this
 * hook fails open — silence, never a broken title.
 */

import { spawn } from 'node:child_process';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';

const ESC = '\u001b';
const BEL = '\u0007';
const CHIME = '/System/Library/Sounds/Glass.aiff';
const FANFARE_DEBOUNCE_MS = 2000;

/** Random .mp3 from `<fanfare dir>/<kind>/`, or null → caller fails open. */
function pickClip(kind) {
  try {
    const base = process.env.CLAUDE_FANFARE_DIR
      ?? path.join(os.homedir(), '.claude', 'sounds', 'fanfare');
    const dir = path.join(base, kind);
    const clips = readdirSync(dir).filter((f) => f.endsWith('.mp3'));
    if (clips.length === 0) return null;
    return path.join(dir, clips[Math.floor(Math.random() * clips.length)]);
  } catch {
    return null;
  }
}

/**
 * Chorus guard: parallel sessions finishing together shouldn't yell over
 * each other. True (skip) if another fanfare started < 2s ago; touches the
 * lockfile when clear to claim the slot.
 */
function fanfarePlayedRecently() {
  const lock = process.env.CLAUDE_FANFARE_LOCK
    ?? path.join(os.tmpdir(), 'claude-fanfare.lock');
  try {
    if (Date.now() - statSync(lock).mtimeMs < FANFARE_DEBOUNCE_MS) return true;
  } catch {}
  try {
    writeFileSync(lock, '');
  } catch {}
  return false;
}

/** Play a sound file, detached. CLAUDE_FANFARE_PLAYER overrides afplay (tests). */
function play(file) {
  const override = process.env.CLAUDE_FANFARE_PLAYER;
  if (!override && process.platform !== 'darwin') return;
  spawn(override || 'afplay', [file], { detached: true, stdio: 'ignore' }).unref();
}

let rawStdin = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { rawStdin += chunk; });
process.stdin.on('error', () => process.exit(0));
process.stdin.on('end', () => main(rawStdin));

function main(raw) {
  let input;
  try {
    input = JSON.parse(raw);
  } catch {
    process.exit(0);
  }

  const { hook_event_name: event, notification_type: type, cwd } = input ?? {};
  if (typeof cwd !== 'string' || cwd.length === 0) process.exit(0);

  let glyph;
  let clipKind = null;
  let chime = false;
  if (event === 'Stop') {
    glyph = '✅';
    clipKind = 'stop';
  } else if (event === 'Notification') {
    if (type === 'permission_prompt' || type === 'agent_needs_input') {
      glyph = '⏸';
      clipKind = 'input';
      chime = true;
    } else if (type === 'idle_prompt') {
      glyph = '✅';
    }
  }
  if (!glyph) process.exit(0);

  if (process.env.CLAUDE_TAB_TITLE_SILENT !== '1') {
    const clip = clipKind === null ? null : pickClip(clipKind);
    if (clip !== null) {
      if (!fanfarePlayedRecently()) play(clip);
    } else if (chime) {
      play(CHIME);
    }
  }

  const title = `${glyph} ${path.basename(cwd)}`;
  process.stdout.write(JSON.stringify({ terminalSequence: `${ESC}]0;${title}${BEL}` }));
  process.exit(0);
}
